### ISSUE TITLE
Enhancement: Minecraft banned/eulaed server detector

### ISSUE THREAD

**Issue by feliscatusmeows** [cornos/Cornos#86]
**Describe the feature/change you want**

Cornos should tell the user when a server on their server list or a server that is being direct connected to has been blocked for eula reasons. https://wiki.vg/Mojang_API#Blocked_Servers shows how a server can be checked, and cornos should read the server list and direct connect text box. Alternitively, add a button for cornos to check when the error for blocked server is returned. 

**Describe alternitives you have tried**

Checking it manually

**Comment by 0x150** [comment]
can do that relatively easily but like why

**Comment by feliscatusmeows** [comment]
why not

**Comment by 0x150** [comment]
because your mom

**Comment by feliscatusmeows** [comment]
Also partially because I couldn't find a tool that can check this

**Comment by FreakingChicken** [comment]
https://ismyserverblocked.com/ can check servers, just type in a server ip and it will tell you if it is blocked or not.

**Comment by feliscatusmeows** [comment]
Neat, would still be useful for cornos to tell me if the "Network is unreachable" error is because the server was EULAed or not.
