### ISSUE TITLE
Enhancement: Boob esp

### ISSUE THREAD

**Issue by Napoleon-ZoomberParts** [cornos/Cornos#88]
I want you to add booba esp.

(And no, Idk how to make such thing or have any examples, just skid sphere code from penis esp and use lwgl bullcrap?? Idk)

**Comment by 0x150** [comment]
why

**Comment by feliscatusmeows** [comment]
why

**Comment by Napoleon-ZoomberParts** [comment]
> why

I like booba

**Comment by Napoleon-ZoomberParts** [comment]
> why

Why not?

**Comment by feliscatusmeows** [comment]
y

**Comment by Napoleon-ZoomberParts** [comment]
> y

Because

**Comment by feliscatusmeows** [comment]
*bonk*

**Comment by Napoleon-ZoomberParts** [comment]
> _bonk_

Next issue will be regarding Pussy and Ass esp

**Comment by feliscatusmeows** [comment]
no, bad

**Comment by Napoleon-ZoomberParts** [comment]
> no, bad

Haram!!!

**Comment by feliscatusmeows** [comment]
please close this as won't add
