### ISSUE TITLE
Compatibility: with SeedCrackerX

### ISSUE THREAD

**Issue by erxdev** [cornos/Cornos#92]
Please search in [the issues page](https://github.com/AriliusClient/Cornos/issues?q=) to make sure this isn't a
duplicate issue.

**Other mods installed**

Cornos 1.5.3
FabricAPI 0.34.6+1.16
SeedCrackerX 0.2.7

**Issue Description**

OreSim doesnt work with SeedCrackerX

**General Information:**

- OS: Windows
- Cornos build date: 08.06
- Java version: 16
- Other system info you think may be useful:
- Launcher (Vanilla or other): MultiMC

**Screenshots**

Just an error "Error doing math", "Something went wrong, you may have, some mods that mess with world generation"

**Comment by 0x150** [comment]
yea its an issue with seedcrackerx for some reason not allowing us to get the world identifier. nothing i can fix

**Comment by 19MisterX98** [comment]
I think I fixed it in one of the latest commits but I'm too lazy to publish a release lol

**Comment by erxdev** [comment]
just upload it to SeedCrackerX repository♥

**Comment by erxdev** [comment]
Or you uploaded it to master branch?

**Comment by 0x150** [comment]
1.16 branch

**Comment by 0x150** [comment]
i think

**Comment by erxdev** [comment]
last commit was 8 days ago (1.16 branch)
